import React from 'react';

import { Typography, Box, Stack, Divider, Button,IconButton } from '@mui/material';

import GitHubIcon from '@mui/icons-material/GitHub';
// import TwitterIcon from '@mui/icons-material/Twitter';
// import InstagramIcon from '@mui/icons-material/Instagram';
import LinkedInIcon from '@mui/icons-material/LinkedIn';


import GlassCard from '../components/GlassCard';

// TODO: Add in git repo and also my socials
const About: React.FC = () => {
  return (
    <>
      <Stack spacing={2} alignItems={'center'}>
        <Box sx={{ maxWidth: 800, m: "auto", p: "auto", width: "90vw" }}>

          <GlassCard>
            <Typography variant="h4" gutterBottom textAlign={'center'}>
              About This Site
            </Typography>
            <Divider />

            <Stack padding={1} spacing={2}>
              <Typography variant='h3' textAlign={'center'} color='red'>
                ⚠️ DISCLAIMER ⚠️
              </Typography>
              <Typography variant="body1">
                This website is satirical and should <strong>NOT</strong> be used for actual investing decisions.
                The financial insights shown here are generated by a large language model (LLM). An AI that has zero real world accountability, no market expertise, and cannot be held liable for making you poor.
              </Typography>
            </Stack>

            <Divider />
            <Typography
              variant="body2"
              color="textSecondary"
              sx={{
                textAlign: 'center',
                marginBottom: 3,
                fontStyle: 'italic',
                opacity: 0.7,
              }}
            >
              TL;DR: None of the content you see here is human reviewed or approved. It's algorithmic, speculative, and purely for entertainment or curiosity. You’ve been warned.
            </Typography>
            <Typography variant="body1" fontWeight="bold">
              Nothing on this website constitutes a recommendation, endorsement, or strategy for any actual investment. By using this site, you acknowledge that any actions you take are entirely at your own risk and that you understand this is a parody project.
            </Typography>

            <Typography variant="h5" gutterBottom sx={{ mt: 4 }}>
              So What <strong>Is</strong> This?
            </Typography>

            <Typography variant="body1" >
              This site uses AI to generate fictional investing advice, loosely inspired by current news and it's previous predictions.
              It periodically gathers public news stories, runs them through a language model, and outputs what the model generates as a "smart" move.
            </Typography>
            <Divider />
            <Stack m={2} spacing={2}>
              <Typography>
                Now that that's clear, head back to the main page to see what an AI enhanced race to poverty would look like
              </Typography>
              <Button variant='contained' href='/'>
                Take me back
              </Button>
            </Stack>

          </GlassCard>

        </Box>
        <Box sx={{ maxWidth: 800, m: "auto", p: "auto", width: "90vw" }}>
          <GlassCard>
            <Typography variant="h6" gutterBottom>
              Check out my socials! And if you know how to code, contribute on GitHub (Please)
            </Typography>

            <Stack direction="row" spacing={2}>
              <IconButton
                component="a"
                href="https://github.com/sean-madu/hot-takes-hedging"
                target="_blank"
                rel="noopener noreferrer"
                color="primary"
              >
                <GitHubIcon />
              </IconButton>
              {/* <IconButton
                component="a"
                href="https://twitter.com/yourusername"
                target="_blank"
                rel="noopener noreferrer"
                color="primary"
              >
                <TwitterIcon />
              </IconButton> */}
              <IconButton
                component="a"
                href="https://www.linkedin.com/in/sean-madu-b8a177261/"
                target="_blank"
                rel="noopener noreferrer"
                color="primary"
              >
                <LinkedInIcon />
              </IconButton>
              {/* <IconButton
                component="a"
                href="https://instagram.com/yourusername"
                target="_blank"
                rel="noopener noreferrer"
                color="primary"
              >
                <InstagramIcon />
              </IconButton> */}
            </Stack>
          </GlassCard>
        </Box>
      </Stack>


    </>

  );
};

export default About;
