import React from 'react';
import { useEffect, useState } from 'react';
import { useQuery } from '@tanstack/react-query';

import { fetchLatestAdvice } from '../api'; 

import {
    Typography,
    Alert,
    Box,
    Link,
    Stack,
    CircularProgress,
} from '@mui/material';

import InvestmentPostsDisplay from '../components/InvestmentPostsDisplay';
import SummaryTicker from '../components/SummaryTicker';

// TODO: Add a nice gradient so the glasst effect looks better
const Home: React.FC = () => {
    const [timeLeft, setTimeLeft] = useState(0);

    const {
        data: advice,
        isLoading,
        isError,
        error,
    } = useQuery({
        queryKey: ['latestAdvice'],
        queryFn: fetchLatestAdvice, 
        staleTime: Infinity,
    });

    let startDate = advice ? advice[0].timestamp : ""
    useEffect(() => {
    const endTime = new Date(startDate).getTime() + 2.5 * 60 * 60 * 1000; // +2:30  in ms

    const updateCountdown = () => {
      const now = new Date().getTime();
      const difference = endTime - now;
      setTimeLeft(difference > 0 ? difference : 0);
    };

    // Initialize countdown immediately
    updateCountdown();

    
    const intervalId = setInterval(updateCountdown, 1000);

    return () => clearInterval(intervalId);
  }, [startDate]);


    const formatTime = (ms: number) => {
    const totalSeconds = Math.floor(ms / 1000);
    const hours = String(Math.floor(totalSeconds / 3600)).padStart(2, '0');
    const minutes = String(Math.floor((totalSeconds % 3600) / 60)).padStart(2, '0');
    const seconds = String(totalSeconds % 60).padStart(2, '0');
    return `${hours}:${minutes}:${seconds}`;
  };

    return (
        <>
            <Box
                alignItems={'center'}
                sx={{
                    m: { xs: 1, md: 2 },
                    p: 0
                }}
            >
                <Typography
                    variant="h2"
                    fontWeight={'bold'}
                    gutterBottom
                    textAlign="center"
                    sx={{ fontSize: { xs: '2.5rem', md: '3.75rem' } }}
                >
                    HEDGE YOUR BETS!
                </Typography>
                <Alert severity='error' sx={{
                    mb: 2,
                    fontSize: { xs: '1rem', md: '1.25rem' }, 
                    padding: { xs: '8px 12px', md: '16px 24px' } 
                }}>
                    ⚠️ <strong>This is NOT financial advice.</strong> All investment suggestions are algorithmically generated by a language model and are meant to be absurd or incorrect.
                    <br />
                    <strong>For entertainment and educational purposes only.</strong>
                    <br />
                    See the full disclaimer on our{" "}
                    <Link href="/about" underline="hover">
                        About page
                    </Link>
                    . Seriously, do NOT invest based on this.
                </Alert>
            </Box>

            {isLoading ? (
                <Box display="flex" justifyContent="center" mt={4}>
                    <CircularProgress />
                </Box>
            ) : isError ? (
                <Alert severity="error" sx={{ m: 2 }}>
                    Failed to load the latest advice: {error instanceof Error ? error.message : 'Unknown error'}
                </Alert>
            ) : advice && advice.length > 0 ? (
                <>
                    <Stack alignItems={'center'} width={'100%'} spacing={1}>
                        <Typography >
                            NEXT UPDATE IN <Box alignContent={'center'} border={1}>
                                <Typography textAlign={'center'} variant='h6' color='error.light'>
                                {formatTime(timeLeft)}
                                </Typography>
                                </Box>
                        </Typography>
                        <Typography sx={{ fontSize: { xs: '0.8rem', md: '1rem' } }}>
                            LAST UPDATE AT A GLANCE
                        </Typography>
                        <SummaryTicker advice={advice[0]['Investment Advice']} speed={80} />
                    </Stack>
                    <InvestmentPostsDisplay posts={advice} />
                </>
            ) : (
                <Typography textAlign="center" color="textSecondary">
                    Latest Advice not found. Something might have gone wrong.
                </Typography>
            )}
        </>

    );
};

export default Home;